export enum PenaltyStatusEnum {
  ANALISE_1 = 'EM ANÁLISE - NOTIFICAÇÃO',
  ANALISE_2= 'EM ANÁLISE - AUTO',
  DEFERIDO = 'DEFERIDO',
  INDEFERIDO_1 = 'INDEFERIDO - RECURSO DE NOTIFICAÇÃO',
  INDEFERIDO_2 = 'INDEFERIDO - REURSO DO AUTO',
}